import Head from 'next/head'
import Navbar from '../Components/Navbar'
import Img from 'next/image'
import scroll from '../assets/scroll.png';
import HINDU from '../assets/HINDU.png';
import TAMIL from '../assets/TAMIL.png';
import BRAINFEED from '../assets/BRAINFEED.png';
import interviews from '../assets/interviews.png';
import podcasts from '../assets/podcasts.png';
import discussions from '../assets/discussions.png';
import blogs from '../assets/blogs.png';
import { Swiper, SwiperSlide } from 'swiper/react';
import Link from 'next/link'
import 'swiper/css';
import 'swiper/css/pagination';
import SwiperCore, { Pagination } from 'swiper';
import img1 from '../assets/image 1.png';
import img2 from '../assets/image 2.png';
import img3 from '../assets/image 3.png';
import Footer from '../Components/Footer';

const keygen = () => Math.random()*1000 

SwiperCore.use([Pagination]);
const CarouselItems = [img1, img2, img3]

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/> 
    <section className="landing-1">
        <div className="container">
        <h1> <span className='base'> We </span> talk, discuss and learn <br /> from <span className='underline'> young </span>
      achievers </h1>
      <div className="no-mobile">
      <p className='invisible'>we do interviews, write blogs, make podcasts and a lot like </p> <p className='young'>young</p>
      <p className="tagline"> we do interviews, write blogs, make podcasts and a lot more with  leaders </p>
    <center>

    <ul className='center'>
      <li>Meet new people and build your network</li>
      <li>Learn and explore the community</li>
      <li>Get inspired from success stories</li>
    </ul>
    </center>
      </div>

      <div className="no-pc">
      We do interviews, write blogs, <br />
make podcasts and a lot more with <br />
 young achievers

    <ul className='justify'>
      <li>Meet new people and build your network</li>
      <li>Learn and explore the community</li>
      <li>Get inspired from success stories</li>
    </ul>

      </div>
      <center>
        <button className="btn btn-3">
          JOIN US
        </button>
      </center>
        </div>
    </section>

        <center>
      <div className="scroll">
        <Img src={scroll} alt="" />
      </div>
        </center>

    <section className="landing-2 container">
      <h2> see whats <span className='base'>buzzing</span>  </h2>
      <div className="tagline dim"> Click on the tags to have a sneak peek into our community </div>
      <div className="buz-grid">
        <div className="buz-grid-item">
          singing 
        </div>
        <div className="buz-grid-item">
          dancer 
        </div>
        <div className="buz-grid-item">
          artist   
        </div>
        <div className="buz-grid-item">
          startup
        </div>
        <div className="buz-grid-item">
          reader 
        </div>
        <div className="buz-grid-item">
          runner 
        </div>
      </div>
      <h2 className='mart-5vh'> Great works get <span className='base'>recognized</span>  </h2>
      <div className="tagline dim"> FEATURED IN </div>

      <div className="row rec">
        <div className="col-lg-4">
          <Img className='mt-minus5' src={HINDU} alt='' />
        </div>
        <div className="col-lg-4">
          <Img className='rec-img mpl-0' src={TAMIL} alt='' />
        </div>
        <div className="col-lg-4">
          <Img className='rec-img' src={BRAINFEED} alt='' />
        </div>
      </div>
    </section> 


    <section className="inspire">
      <div className="container">
        <center><h2>Want to join our <span className='underline'>inspiring</span> community ?</h2></center>
        <div className="row pl-5vw">
          <div className="col-lg-6 order3">
            <span className="l-tilt community">Interviews</span>
            <i className="bi bi-person-square"></i>
            <p className='fw-600'> Watch and learn from other's experiences </p> 
            <p className="dim">
            learning from successful people will <br />
help us in nurturing ourselves into <br />
better human beings
            </p>
            <div className="btn inb btn-2">WATCH NOW!</div>
          </div>
          <div className="col-lg-6 order2">
            <center>
            <Img src={interviews} alt="" className="ins-img" />
            </center>
          </div>
        </div>

        <div className="row r-2">
        <div className="col-lg-6">
            <center>
            <Img  src={podcasts} alt="" className="ins-img ins-img-2" />
            </center>
          </div>
          <div className="col-lg-6 pl-5vw-2">
            <span className="r-tilt community">Podcasts</span>
            <i className="bi bi-headset"></i>
            <p className='fw-600'>No time to watch? then listen!</p>
            <p className="dim">Not having enough time to watch <br />
our interviews ? that’s fine we’ve got <br />
podcasts too!
             </p> 
             <div className="btn inb btn-2">LISTEN NOW!</div>
          </div>
        </div>


        <div className="row pl-5vw r-2">
          <div className="col-lg-6 order3">
            <span className="l-tilt community">Discussions </span>
            <i className="bi bi-person-square"></i>
            <p className='fw-600'> Share your thoughts, discuss and debate</p> 
            <p className="dim">
            You can contribute to ongoing discussions <br />
or you can initiate your own debate, support <br />
people and react to their comments
            </p>
            <div className="btn inb btn-2">DISCUSS NOW!</div>
          </div>
          <div className="col-lg-6 order2">
            <center>
            <Img src={discussions} alt="" className="ins-img" />
            </center>
          </div>
        </div>

        <div className="row r-2">
        <div className="col-lg-6">
            <center>
            <Img  src={blogs} alt="" className="ins-img ins-img-2" />
            </center>
          </div>
          <div className="col-lg-6 pl-5vw-2">
            <span className="r-tilt community">Blogs </span>
            <i className="bi bi-headset"></i>
            <p className='fw-600'>Read and widen your knowledge</p>
            <p className="dim">Not having enough time to watch <br />
our interviews ? that’s fine we’ve got <br />
blogs too!
             </p> 
             <div className="btn inb btn-2">READ NOW!</div> 
          </div>
        </div>
      </div>
    </section>

    <section className="landing-3 container">
      <center>
    <h2> spreading the stories of young  <span className='base'>entreprene</span>  </h2>
      </center>
      <Swiper
       slidesPerView={3}  
       spaceBetween={30}  
       pagination = {true}
       grabCursor={true}
       className='myswiperhomepage'
       breakpoints={{
         200:{
           width: 360,
           slidesPerView:1
         },
        640: {
          width: 500,
          slidesPerView: 2,
        },
        768: {
          width: 768,
          slidesPerView: 2,
        },
      }}>
            {CarouselItems.map( (img) =>(
              <SwiperSlide key={keygen()}> 
                <Img src={img} alt='' className='carousel-image' /> 
              </SwiperSlide>
            ))}
        </Swiper>
    </section>
    <section className="contact">
      <div className="container">
      <div className="row">
        <div className="col-lg-7 pl-5vv">
        <h3>want to share <span className='yourstory'>your story</span> with us?</h3>
        <h4 className='dim'>That’s simple, just write to us and we’ll look into it</h4>
        <form>
            <label htmlFor="name">Name</label> 
            <input type="text" name="name" id="name" />
            <label htmlFor="contact">Contact</label>
            <input type="text" name="contact" id="contact" placeholder='features of your land' />
            <label htmlFor="introduce">Inroduce Yourself</label>
            <textarea name="introduce" id="introduce" cols="24" rows="8"></textarea>
            <input type="submit" className='btn submit btn-2' value='SUBMIT'/>
        </form>
        </div>
        <div className="col-lg-5">
              <h3>Be the <span className="base">1st</span> one to know !</h3>
              <h5 className="dim">We run a newsletter too. Get latest <br /> updates every week</h5>
              <button className="btn subscribe btn-1">SUBSCRIBE </button> &nbsp; <span className='dim'>FREE!</span> 
        </div>
      </div>
      </div>
    </section> 
    <Footer />
    </>
  )
}
